# Generated by Django 5.1.6 on 2025-03-01 19:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmeModel',
            fields=[
                ('id_imdb', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('titulo_filme', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('diretor', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('sinopse', models.TextField()),
                ('nota_imdb', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='FavoritoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_usuario', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('filme_favorito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fav_filmes.filmemodel')),
            ],
            options={
                'unique_together': {('usuario', 'filme_favorito')},
            },
        ),
    ]
