# Generated by Django 5.1.6 on 2025-03-01 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fav_filmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritomodel',
            name='nota_usuario',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='filmemodel',
            name='nota_imdb',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
